name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

#      - name: Setup Pages 📄
#        uses: actions/configure-pages@v4

      - name: Setup Node 📦
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Java ☕
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build game data 🎮
        run: java -jar ./GameCalendarVerifier-1.0-SNAPSHOT-all.jar

      - name: Build Fonts 🔠
        run: |
          cd font_builder
          yarn
          node ./build_fonts.js

      - name: Install and Build 📅
        run: |
          yarn
          node ./build_ics.js
          yarn build

      - name: Upload COS 🚀
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rs dist/ /
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          bucket: ${{ secrets.TENCENT_BUCKET }}
          region: ap-guangzhou

      - name: Flush CDN 🧹
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          chmod +x ./refresh_cdn.sh
          ./refresh_cdn.sh
