name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Pages 🔧
        uses: actions/configure-pages@v4

      - name: Setup Node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Java 🔧
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build game data 🔧
        run: java -jar ./GameCalendarVerifier-1.0-SNAPSHOT-all.jar

      - name: Install and Build 🔧
        run: |
          yarn
          node ./build_ics.js
          yarn build

      - name: Upload artifact 🚀
        run: |
          chmod +x ./coscli-linux
          cd dist
          ../coscli-linux sync ./ cos://gaming-epochs-1251466821/ -c ../.cos.yaml -r -e cos.ap-guangzhou.myqcloud.com -i ${{ secrets.TENCENT_SECRET_ID }} -k ${{ secrets.TENCENT_SECRET_KEY }}
